const SpecialActionTypes = {
    ADD_ITEM: 'ADD_ITEM',
    UPDATE_ITEM: 'UPDATE_ITEM',
    FETCH_SPECIAL_SUCCESS: 'FETCH_SPECIAL_SUCCESS',
    FETCH_SPECIAL_PENDING: 'FETCH_SPECIAL_PENDING',
    FETCH_SPECIAL_ERROR: 'FETCH_SPECIAL_ERROR'
}

export default SpecialActionTypes;